name: CMake


# nvm lmao
on:
  push:
    branches: [ "unstable" ]
  pull_request:
    branches: [ "unstable" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run CMake
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update repositories
      run: sudo apt update

    - name: Setup CMake Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

    - name: Build
      # Build your program with the given configuration
      run: |
        cd build
        make

