name: CMake


# nvm lmao
on:
  push:
    branches: [ "unstable" ]
  pull_request:
    branches: [ "unstable" ]

env:
  NEOSKYE_USE_SYSTEM_SFML: 1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run CMake
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update repositories
      run: sudo apt update
    
    - name: Install SFML
      run: sudo apt install libsfml-dev
    - name: Setup Cmake Build
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      # Build your program with the given configuration
      run: |
        cd build
        make
