name: 'Submodule Notify Parent'

on:
  push:
    branches:
      - cs-rewrite    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    name: 'Submodule Notify Parent'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    permissions:
      actions: read/write

    steps:
    - name: Github REST API Call
      env:
        CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PARENT_REPO: neoskye-team/neoskye
        PARENT_BRANCH: main
        WORKFLOW_ID: 49601324
      run: |
        curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
